// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53DWFVWiQkWiBdfjiOHuIse8sYiC6iKM',
    appId: '1:502074644917:web:6e5ae3e2db74f7807021fc',
    messagingSenderId: '502074644917',
    projectId: 'habittracker-d54c4',
    authDomain: 'habittracker-d54c4.firebaseapp.com',
    storageBucket: 'habittracker-d54c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqlyFxMVAhESbqHHZEg9hGeO3AiPBHdcs',
    appId: '1:502074644917:android:ef38f3e2fa5c1a347021fc',
    messagingSenderId: '502074644917',
    projectId: 'habittracker-d54c4',
    storageBucket: 'habittracker-d54c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXczk53ko0LeDzLUbHvVqC7rsdlhWvW4',
    appId: '1:502074644917:ios:f419dd6ff6283a5b7021fc',
    messagingSenderId: '502074644917',
    projectId: 'habittracker-d54c4',
    storageBucket: 'habittracker-d54c4.firebasestorage.app',
    iosClientId: '502074644917-qsddmdpt9j7ksofnde7p614lk8h9a164.apps.googleusercontent.com',
    iosBundleId: 'com.jumapaul.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXczk53ko0LeDzLUbHvVqC7rsdlhWvW4',
    appId: '1:502074644917:ios:f419dd6ff6283a5b7021fc',
    messagingSenderId: '502074644917',
    projectId: 'habittracker-d54c4',
    storageBucket: 'habittracker-d54c4.firebasestorage.app',
    iosClientId: '502074644917-qsddmdpt9j7ksofnde7p614lk8h9a164.apps.googleusercontent.com',
    iosBundleId: 'com.jumapaul.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD53DWFVWiQkWiBdfjiOHuIse8sYiC6iKM',
    appId: '1:502074644917:web:3e4d89bad75e6d347021fc',
    messagingSenderId: '502074644917',
    projectId: 'habittracker-d54c4',
    authDomain: 'habittracker-d54c4.firebaseapp.com',
    storageBucket: 'habittracker-d54c4.firebasestorage.app',
  );
}
